# https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/service_mesh_install/service-mesh-installation#supported-configurations
#
#
# Modify the Kiali Username/Password - This is the login for the Kiali console and is not related to the OCP logins
# Modify the Openshift Launcher user - This is the user you want to launch the Fabric8 Launcher
# Modify the GitHub user/token - Github account you want to use to run the Fabric8 Launcher
#
apiVersion: istio.openshift.com/v1alpha3
kind: ControlPlane
metadata:
  name: basic-install
spec:
  launcher:
    enabled: true
    # specify the url to master, e.g. https://master.some.domain.com:443
    # Note that you do note need the URL if you're deploying the launcher to the same cluster as service mesh
    #LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL: 
    # Your GitHub username
    LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME: 
    # Your GitHub Mission Control access token
    LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN: 

  threeScale:
    enabled: false

  istio:
    global:
      hub: openshift-istio-tech-preview/
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      mtls: true

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        ior_enabled: false

    mixer:
      policy:
        autoscaleEnabled: false

      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    kiali:
      enabled: true
#      hub: openshift-istio-tech-preview
      dashboard:
        user: admin
        passphrase: admin
    tracing:
      enabled: true
