apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
spec:
  launcher:
    enabled: true
    # specify the url to master, e.g. https://master.some.domain.com:443
    # Note that you do note need the URL if you're deploying the launcher to the same cluster as service mesh
    #LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL: 
    # Your GitHub username
    LAUNCHER_MISSIONCONTROL_GITHUB_USERNAME: 
    # Your GitHub Mission Control access token
    LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN: 

  threeScale:
    enabled: false

  istio:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      mtls: true
      disablePolicyChecks: false

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        ior_enabled: false

    mixer:
      policy:
        autoscaleEnabled: false

      telemetry:
          autoscaleEnabled: false
          resources:
            requests:
              cpu: 100m
              memory: 1G
            limits:
              cpu: 500m
              memory: 4G

      pilot:
        autoscaleEnabled: false
        traceSampling: 100.0
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    kiali:
      enabled: true
#      hub: openshift-istio-tech-preview
      dashboard:
        user: admin
        passphrase: admin
    tracing:
      enabled: true
