apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
spec:
  capacity:
    storage: 50Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle 
  nfs: 
    path: /volume1/OpenShift/storage/pv
    server: nfs-server.internal.yourdomain.com
    readOnly: false
  storageClassName: normal
